#!/usr/bin/env ruby

# gems
require 'open-uri'
require 'json'
require 'rubygems/package'
require 'zlib'
require 'optparse'

# Local Modules
require_relative 'modules/help'
require_relative 'modules/install'
require_relative 'modules/search'
require_relative 'modules/update'
require_relative 'modules/package_extractor'

# include function from modules
class Main
  include Help
  include Install
  include Search
  include Update

  def initialize
    raise 'Requires ruby >= 2.7.0' if RUBY_VERSION <= '2.7.0'

    options = {}
    OptionParser.new do |opts|
      opts.banner = 'Usage: yogurt [options]'

      update if ARGV.empty?

      opts.on('-h', '--help', 'Show help menu.') do
        help
      end

      opts.on('-S', 'Install a specific package.') do
        install_pkg
      end

      opts.on('-U', 'Perform an update verification.') do
        update
      end

      opts.on('--version', 'Show yogurt version.') do
        puts 'yogurt aur helper version: 4.1'
      end
    end.parse!
  end
end

Main.new
